{
 "title": "Telegraf Linux",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "prom", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(internal_gather_errors, job)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(internal_gather_errors{job=~\"$job\"}, host)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(internal_agent_gather_errors{host=~\"$host\"}, instance)"
    }
   },
   {
    "name": "disk_re",
    "query": "^(hd[a-z]*|vd[a-z]*|sd[a-z]*|nvme[0-9]n[0-9])$"
   },
   {
    "name": "interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "chip",
    "query": {
     "query": "label_values(sensors_temp_input{instance=~\"$instance\"}, chip)"
    }
   },
   {
    "name": "GPU",
    "query": {
     "query": "label_values(nvidia_smi_utilization_gpu{instance=~\"$instance\"}, uuid)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "system_load1{host=~\"$host\"}",
     "legendFormat": "load1"
    },
    {
     "expr": "system_load5{host=~\"$host\"}",
     "legendFormat": "load5"
    },
    {
     "expr": "system_load15{host=~\"$host\"}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mem_free{host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "free"
    },
    {
     "expr": "mem_cached{host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "mem_buffered{host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "buffered"
    },
    {
     "expr": "mem_shared{host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "shared"
    },
    {
     "expr": "mem_used{host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu_usage_idle{cpu=\"cpu-total\", host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "cpu_usage_guest{cpu=\"cpu-total\", host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "guest"
    },
    {
     "expr": "cpu_usage_guest_nice{cpu=\"cpu-total\", host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "guest_nice"
    },
    {
     "expr": "cpu_usage_iowait{cpu=\"cpu-total\", host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "iowait"
    },
    {
     "expr": "cpu_usage_irq{cpu=\"cpu-total\", host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "irq"
    },
    {
     "expr": "cpu_usage_nice{cpu=\"cpu-total\", host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "nice"
    },
    {
     "expr": "cpu_usage_softirq{cpu=\"cpu-total\", host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "softirq"
    },
    {
     "expr": "cpu_usage_steal{cpu=\"cpu-total\", host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "steal"
    },
    {
     "expr": "cpu_usage_system{cpu=\"cpu-total\", host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "cpu_usage_user{cpu=\"cpu-total\", host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Entropy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kernel_entropy_avail{host=~\"$host\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Process & threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "processes_total_threads{host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "threads"
    },
    {
     "expr": "processes_total{host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "processes"
    }
   ]
  },
  {
   "title": "FD",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "linux_sysctl_fs_file_nr{host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "file"
    },
    {
     "expr": "linux_sysctl_fs_dentry_nr{host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "dentry"
    },
    {
     "expr": "linux_sysctl_fs_inode_nr{host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "inode"
    },
    {
     "expr": "linux_sysctl_fs_aio_nr{host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "aio"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "processes_dead{host=~\"$host\"}",
     "legendFormat": "dead"
    },
    {
     "expr": "processes_blocked{host=~\"$host\"}",
     "legendFormat": "blocked"
    },
    {
     "expr": "processes_idle{host=~\"$host\"}",
     "legendFormat": "idel"
    },
    {
     "expr": "processes_paging{host=~\"$host\"}",
     "legendFormat": "paging"
    },
    {
     "expr": "processes_running{host=~\"$host\"}",
     "legendFormat": "running"
    },
    {
     "expr": "processes_sleeping{host=~\"$host\"}",
     "legendFormat": "sleeping"
    },
    {
     "expr": "processes_stopped{host=~\"$host\"}",
     "legendFormat": "stopped"
    },
    {
     "expr": "processes_unknown{host=~\"$host\"}",
     "legendFormat": "unknown"
    },
    {
     "expr": "processes_zombies{host=~\"$host\"}",
     "legendFormat": "zombies"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "processes_total_threads{host=~\"$host\"}",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "system_uptime{host=~\"$host\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "OOM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(kernel_vmstat_oom_kill{host=~\"$host\", instance=~\"$instance\"}[$interval])"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_n_users{host=~\"$host\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Forked Process",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "targets": [
    {
     "expr": "rate(kernel_processes_forked{host=~\"$host\"}[$interval])",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Conntrack Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "conntrack_ip_conntrack_count{host=~\"$host\", instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mem_free{host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "free"
    },
    {
     "expr": "mem_cached{host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "mem_buffered{host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "buffered"
    },
    {
     "expr": "mem_slab{host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "slab"
    },
    {
     "expr": "mem_total{host=~\"$host\", instance=~\"$instance\"} - mem_buffered - mem_cached - mem_free - mem_slab",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Memory available",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mem_available{host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mem_cached{host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "cache"
    },
    {
     "expr": "mem_buffered{host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "buffered"
    },
    {
     "expr": "mem_shared{host=~\"$host\", instance=~\"$instance\"}",
     "legendFormat": "shared"
    }
   ]
  },
  {
   "title": "Page in/out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kernel_vmstat_pgpgin{host=~\"$host\",  instance=~\"$instance\"}[$interval])",
     "legendFormat": "in"
    },
    {
     "expr": "rate(kernel_vmstat_pgpgout{host=~\"$host\",  instance=~\"$instance\"}[$interval])",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "OOM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kernel_vmstat_oom_kill{host=~\"$host\",  instance=~\"$instance\"}[$interval])",
     "legendFormat": "in"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mem_swap_free{host=~\"$host\",  instance=~\"$instance\"}",
     "legendFormat": "free"
    },
    {
     "expr": "mem_swap_total{host=~\"$host\",  instance=~\"$instance\"} - mem_swap_free{host=~\"$host\",  instance=~\"$instance\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Swap In&Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(swap_in{host=~\"$host\",  instance=~\"$instance\"}[$interval])",
     "legendFormat": "in"
    },
    {
     "expr": "irate(swap_out{host=~\"$host\",  instance=~\"$instance\"}[$interval])",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Swap in/out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kernel_vmstat_pswpin{host=~\"$host\",  instance=~\"$instance\"}[$interval])",
     "legendFormat": "in"
    },
    {
     "expr": "rate(kernel_vmstat_pswpout{host=~\"$host\",  instance=~\"$instance\"}[$interval])",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Slab",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kernel_vmstat_nr_slab_reclaimable{host=~\"$host\",  instance=~\"$instance\"} * 4096",
     "legendFormat": "reclaimable"
    },
    {
     "expr": "kernel_vmstat_nr_slab_unreclaimable{host=~\"$host\",  instance=~\"$instance\"} * 4096",
     "legendFormat": "unreclaimable"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Disk Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(diskio_write_bytes{host=~\"$host\", name=~\"$disk_re\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ name }} - write"
    },
    {
     "expr": "rate(diskio_read_bytes{host=~\"$host\", name=~\"$disk_re\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ name }} - read"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(diskio_writes{host=~\"$host\", name=~\"$disk_re\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ name }} - write"
    },
    {
     "expr": "rate(diskio_reads{host=~\"$host\", name=~\"$disk_re\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ name }} - read"
    }
   ]
  },
  {
   "title": "Disk IO Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(diskio_io_time{host=~\"$host\", name=~\"$disk_re\", instance=~\"$instance\"}[$interval]) / 1000",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Disk Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(diskio_write_time{host=~\"$host\", name=~\"$disk_re\", instance=~\"$instance\"}[$interval]) / 1000",
     "legendFormat": "{{ name }} - write"
    },
    {
     "expr": "irate(diskio_read_time{host=~\"$host\", name=~\"$disk_re\", instance=~\"$instance\"}[$interval]) / 1000",
     "legendFormat": "{{ name }} - read"
    }
   ]
  },
  {
   "title": "Filesystem Avail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "disk_free{host=~\"$host\",  instance=~\"$instance\"}",
     "legendFormat": "{{ path }} "
    }
   ]
  },
  { "title": "NIC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "PPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(net_packets_sent{host=~\"$host\",  instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{ interface }} - sent"
    },
    {
     "expr": "rate(net_packets_recv{host=~\"$host\", instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{ interface }} - recv"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(net_bytes_sent{host=~\"$host\", instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{ interface }} - sent"
    },
    {
     "expr": "rate(net_bytes_recv{host=~\"$host\", instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{ interface }} - recv"
    }
   ]
  },
  {
   "title": "Drop",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(net_drop_in{host=~\"$host\", instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{ interface }} - in"
    },
    {
     "expr": "rate(net_drop_out{host=~\"$host\", instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{ interface }} - out"
    }
   ]
  },
  {
   "title": "Error",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(net_err_in{host=~\"$host\", instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{ interface }} - in"
    },
    {
     "expr": "rate(net_err_out{host=~\"$host\", instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{ interface }} - out"
    }
   ]
  },
  { "title": "Net Stat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "TCP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "netstat_tcp_close{host=~\"$host\",  instance=~\"$instance\"}",
     "legendFormat": "close"
    },
    {
     "expr": "netstat_tcp_close_wait{host=~\"$host\",  instance=~\"$instance\"}",
     "legendFormat": "close wait"
    },
    {
     "expr": "netstat_tcp_closing{host=~\"$host\",  instance=~\"$instance\"}",
     "legendFormat": "closing"
    },
    {
     "expr": "netstat_tcp_established{host=~\"$host\",  instance=~\"$instance\"}",
     "legendFormat": "established"
    },
    {
     "expr": "netstat_tcp_fin_wait1{host=~\"$host\",  instance=~\"$instance\"}",
     "legendFormat": "fin wait 1"
    },
    {
     "expr": "netstat_tcp_fin_wait2{host=~\"$host\",  instance=~\"$instance\"}",
     "legendFormat": "fin wait 2"
    },
    {
     "expr": "netstat_tcp_last_ack{host=~\"$host\",  instance=~\"$instance\"}",
     "legendFormat": "lask ack"
    },
    {
     "expr": "netstat_tcp_listen{host=~\"$host\",  instance=~\"$instance\"}",
     "legendFormat": "listen"
    },
    {
     "expr": "netstat_tcp_none{host=~\"$host\",  instance=~\"$instance\"}",
     "legendFormat": "none"
    },
    {
     "expr": "netstat_tcp_syn_recv{host=~\"$host\",  instance=~\"$instance\"}",
     "legendFormat": "syn_recv"
    },
    {
     "expr": "netstat_tcp_syn_sent{host=~\"$host\",  instance=~\"$instance\"}",
     "legendFormat": "syn_sent"
    },
    {
     "expr": "netstat_tcp_time_wait{host=~\"$host\",  instance=~\"$instance\"}",
     "legendFormat": "time_wait"
    },
    {
     "expr": "netstat_tcp_time_wait{host=~\"$host\",  instance=~\"$instance\"}",
     "legendFormat": "time_wait"
    }
   ]
  },
  {
   "title": "TCP Retrans",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(net_tcp_retranssegs{host=~\"$host\",  instance=~\"$instance\"}[$interval])",
     "legendFormat": "socket"
    }
   ]
  },
  {
   "title": "UDP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "netstat_udp_socket{host=~\"$host\",  instance=~\"$instance\"}",
     "legendFormat": "socket"
    }
   ]
  },
  { "title": "GPU for $GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 }, "repeat": "GPU" },
  {
   "title": "GPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu{host=~\"$host\", instance=~\"$instance\", uuid=~\"$GPU\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg(nvidia_smi_memory_free{host=~\"$host\", instance=~\"$instance\", uuid=~\"$GPU\"}) by (name)",
     "legendFormat": "free"
    },
    {
     "expr": "avg(nvidia_smi_memory_used{host=~\"$host\", instance=~\"$instance\", uuid=~\"$GPU\"}) by (name)",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(nvidia_smi_temperature_gpu{host=~\"$host\", instance=~\"$instance\", uuid=~\"$GPU\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Fan",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(nvidia_smi_fan_speed{host=~\"$host\", instance=~\"$instance\", uuid=~\"$GPU\"}) by (name)",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Power State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(nvidia_smi_pstate{host=~\"$host\", instance=~\"$instance\", uuid=~\"$GPU\"}) by (name)",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Clocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(nvidia_smi_clocks_current_graphics{host=~\"$host\", instance=~\"$instance\", uuid=~\"$GPU\"}) by (name)",
     "legendFormat": "graphics"
    },
    {
     "expr": "avg(nvidia_smi_clocks_current_memory{host=~\"$host\", instance=~\"$instance\", uuid=~\"$GPU\"}) by (name)",
     "legendFormat": "memory"
    },
    {
     "expr": "avg(nvidia_smi_clocks_current_sm{host=~\"$host\", instance=~\"$instance\", uuid=~\"$GPU\"}) by (name)",
     "legendFormat": "sm"
    },
    {
     "expr": "avg(nvidia_smi_clocks_current_video{host=~\"$host\", instance=~\"$instance\", uuid=~\"$GPU\"}) by (name)",
     "legendFormat": "video"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(nvidia_smi_power_draw{host=~\"$host\", instance=~\"$instance\"}) by (name)",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  { "title": "Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Fan",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "sensors_fan_input{host=~\"$host\"}",
     "legendFormat": "{{ feature }}"
    }
   ]
  },
  {
   "title": "IN",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "sensors_in_input{host=~\"$host\"}",
     "legendFormat": "{{ feature }}"
    }
   ]
  },
  {
   "title": "Temp  $chip",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 91 },
   "repeat": "chip",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sensors_temp_input{host=~\"$host\", chip=~\"$chip\"}",
     "legendFormat": "{{ feature }}"
    }
   ]
  },
  {
   "title": "Temp ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "temp_temp{host=~\"$host\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "Internal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(internal_gather_errors{host=~\"$host\", instance=~\"$instance\"}[10m]) > 0",
       "legendFormat": "{{ input }}"
      }
     ]
    },
    {
     "title": "Gather time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "internal_gather_gather_time_ns{host=~\"$host\", instance=~\"$instance\"}",
       "legendFormat": "{{ input }}"
      }
     ]
    },
    {
     "title": "Metrics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk(5, rate(internal_gather_metrics_gathered{host=~\"$host\", instance=~\"$instance\"}[10m]))",
       "legendFormat": "{{ input }}"
      }
     ]
    }
   ]
  }
 ]
}