{
 "title": "Telegraf Linux Summary",
 "tags": [ "telegraf" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "hostname",
    "query": {
     "query": "label_values(internal_agent_gather_errors, host)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(internal_agent_gather_errors{host=~\"$hostname\"}, instance)"
    }
   },
   {
    "name": "internal",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "disk_re",
    "query": "^(hd[a-z]*|vd[a-z]*|sd[a-z]*|nvme[0-9]n[0-9])$"
   },
   {
    "name": "copy_of_copy_of_internal",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "NFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(nfsstat_bytes{host=~\"$hostname\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{mountpoint}} - {{ operation }}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(nfsstat_ops{host=~\"$hostname\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{mountpoint}} - {{ operation }}"
    }
   ]
  },
  {
   "title": "Time",
   "type": "timeseries",
   "description": "exe (integer, miliseconds) - The number of miliseconds it took to process the operations.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(nfsstat_exe{host=~\"$hostname\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{mountpoint}} - {{ operation }}"
    }
   ]
  },
  { "title": "Nvidia", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "GPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(nvidia_smi_utilization_gpu{host=~\"$hostname\", instance=~\"$instance\"}) by (uuid)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg(nvidia_smi_memory_free{host=~\"$hostname\", instance=~\"$instance\"}) by (name)",
     "legendFormat": "free"
    },
    {
     "expr": "avg(nvidia_smi_memory_used{host=~\"$hostname\", instance=~\"$instance\"}) by (name)",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(nvidia_smi_utilization_memory{host=~\"$hostname\", instance=~\"$instance\"} / 100) by (uuid)",
     "legendFormat": "pull-value"
    },
    {
     "expr": "avg(nvidia_smi_memory_used{host=~\"$hostname\", instance=~\"$instance\"} / nvidia_smi_memory_total ) by (uuid)",
     "legendFormat": "cacl-value"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(nvidia_smi_temperature_gpu{host=~\"$hostname\", instance=~\"$instance\"}) by (uuid)",
     "legendFormat": "{{ uuid }}"
    }
   ]
  },
  {
   "title": "Fan",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(nvidia_smi_fan_speed{host=~\"$hostname\", instance=~\"$instance\"}) by (uuid)",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_n_users{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "users"
    },
    {
     "expr": "system_n_cpus{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load1{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "load1"
    },
    {
     "expr": "system_load5{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "load5"
    },
    {
     "expr": "system_load15{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "Context",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(kernel_context_switches{host=~\"$hostname\", instance=~\"$instance\"}[$internal])",
     "legendFormat": "context"
    },
    {
     "expr": "irate(kernel_interrupts{host=~\"$hostname\", instance=~\"$instance\"}[$internal])",
     "legendFormat": "interrupts"
    }
   ]
  },
  {
   "title": "Process",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "processes_idle{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "processes_blocked{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "blocked"
    },
    {
     "expr": "processes_dead{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "dead"
    },
    {
     "expr": "processes_paging{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "paging"
    },
    {
     "expr": "processes_running{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "running"
    },
    {
     "expr": "processes_zombies{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "zombies"
    },
    {
     "expr": "processes_sleeping{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "sleeping"
    },
    {
     "expr": "processes_stopped{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "stopped"
    },
    {
     "expr": "processes_unknown{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "unknown"
    }
   ]
  },
  {
   "title": "Process & threads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "processes_total_threads{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "threads"
    },
    {
     "expr": "processes_total{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "processes"
    }
   ]
  },
  {
   "title": "New forked process",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(kernel_processes_forked{host=~\"$hostname\", instance=~\"$instance\"}[$internal])",
     "legendFormat": "forked"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mem_free{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "free"
    },
    {
     "expr": "mem_cached{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "mem_buffered{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "buffered"
    },
    {
     "expr": "mem_shared{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "shared"
    },
    {
     "expr": "mem_used{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Memory Avail",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mem_total - mem_available{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "inuse"
    },
    {
     "expr": "mem_available{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "avail"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "swap_free{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "free"
    },
    {
     "expr": "swap_used{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(diskio_write_bytes{host=~\"$hostname\", name=~\"$disk_re\", instance=~\"$instance\"}[$internal])",
     "legendFormat": "{{ name }} - write"
    },
    {
     "expr": "irate(diskio_read_bytes{host=~\"$hostname\", name=~\"$disk_re\", instance=~\"$instance\"}[$internal])",
     "legendFormat": "{{ name }} - read"
    }
   ]
  },
  {
   "title": "FS Free (Percent)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "disk_free{host=~\"$hostname\", instance=~\"$instance\"} / disk_total",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "FS Free",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "disk_free{host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cpu_usage_idle{cpu=\"cpu-total\", host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "cpu_usage_guest{cpu=\"cpu-total\", host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "guest"
    },
    {
     "expr": "cpu_usage_guest_nice{cpu=\"cpu-total\", host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "guest_nice"
    },
    {
     "expr": "cpu_usage_iowait{cpu=\"cpu-total\", host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "iowait"
    },
    {
     "expr": "cpu_usage_irq{cpu=\"cpu-total\", host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "irq"
    },
    {
     "expr": "cpu_usage_nice{cpu=\"cpu-total\", host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "nice"
    },
    {
     "expr": "cpu_usage_softirq{cpu=\"cpu-total\", host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "softirq"
    },
    {
     "expr": "cpu_usage_steal{cpu=\"cpu-total\", host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "steal"
    },
    {
     "expr": "cpu_usage_system{cpu=\"cpu-total\", host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "cpu_usage_user{cpu=\"cpu-total\", host=~\"$hostname\", instance=~\"$instance\"}",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(diskio_writes{host=~\"$hostname\", name=~\"$disk_re\", instance=~\"$instance\"}[$internal])",
     "legendFormat": "{{ name }} - write"
    },
    {
     "expr": "irate(diskio_reads{host=~\"$hostname\", name=~\"$disk_re\", instance=~\"$instance\"}[$internal])",
     "legendFormat": "{{ name }} - read"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "system_uptime{host=~\"$hostname\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Entropy",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kernel_entropy_avail{host=~\"$hostname\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "RabbitMQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message Speed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(rabbitmq_overview_messages_delivered{host=~\"$hostname\"}[$internal])",
       "legendFormat": "delivered"
      },
      {
       "expr": "irate(rabbitmq_overview_messages_published{host=~\"$hostname\"}[$internal])",
       "legendFormat": "published"
      }
     ]
    },
    {
     "title": "Blocked Message",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rabbitmq_overview_messages{host=~\"$hostname\"}",
       "legendFormat": "message"
      }
     ]
    },
    {
     "title": "Queue",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rabbitmq_overview_queues{host=~\"$hostname\"}",
       "legendFormat": "message"
      }
     ]
    },
    {
     "title": "Exchanges",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 13, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rabbitmq_overview_exchanges{host=~\"$hostname\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Channel",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rabbitmq_overview_channels{host=~\"$hostname\"}",
       "legendFormat": "channel"
      }
     ]
    },
    {
     "title": "nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rabbitmq_node_running{host=~\"$hostname\"}",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 3, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rabbitmq_node_uptime{host=~\"$hostname\"}",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "used memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rabbitmq_node_mem_used{host=~\"$hostname\"}",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Consumers",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 13, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rabbitmq_overview_consumers{host=~\"$hostname\"}",
       "legendFormat": "consumers"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rabbitmq_node_proc_used{host=~\"$hostname\"}",
       "legendFormat": "{{ node }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memcached",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "memcached_curr_connections{host=~\"$hostname\"}",
       "legendFormat": "connection"
      }
     ]
    },
    {
     "title": "Write and read speed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(memcached_bytes_written{host=~\"$hostname\"}[$internal])",
       "legendFormat": "written"
      },
      {
       "expr": "irate(memcached_bytes_read{host=~\"$hostname\"}[$internal])",
       "legendFormat": "read"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "graph",
     "gridPos": { "h": 8, "w": 3, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "memcached_uptime{host=~\"$hostname\"}",
       "legendFormat": "connection"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 3, "x": 15, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "memcached_threads{host=~\"$hostname\"}",
       "legendFormat": "threads"
      }
     ]
    },
    {
     "title": "Get hits and misses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(memcached_get_hits{host=~\"$hostname\"}[$internal])",
       "legendFormat": "hits"
      },
      {
       "expr": "irate(memcached_get_misses{host=~\"$hostname\"}[$internal])",
       "legendFormat": "misses"
      }
     ]
    },
    {
     "title": "used bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "memcached_bytes{host=~\"$hostname\"}",
       "legendFormat": "cur bytes"
      },
      {
       "expr": "memcached_limit_maxbytes{host=~\"$hostname\"}",
       "legendFormat": "max bytes"
      }
     ]
    },
    {
     "title": "Cmd",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(memcached_cmd_set{host=~\"$hostname\"}[$internal])",
       "legendFormat": "set"
      },
      {
       "expr": "irate(memcached_cmd_get{host=~\"$hostname\"}[$internal])",
       "legendFormat": "get"
      },
      {
       "expr": "irate(memcached_cmd_touch{host=~\"$hostname\"}[$internal])",
       "legendFormat": "touch"
      },
      {
       "expr": "irate(memcached_cmd_flush{host=~\"$hostname\"}[$internal])",
       "legendFormat": "flush"
      }
     ]
    },
    {
     "title": "Items",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "memcached_curr_items{host=~\"$hostname\"}",
       "legendFormat": "cur items"
      }
     ]
    },
    {
     "title": "touch hit and miss",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(memcached_touch_hits{host=~\"$hostname\"}[10m])",
       "legendFormat": "hits"
      },
      {
       "expr": "irate(memcached_touch_misses{host=~\"$hostname\"}[10m])",
       "legendFormat": "misses"
      }
     ]
    }
   ]
  },
  {
   "title": "IPMI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Watt",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ipmi_sensor_value{host=~\"$hostname\", unit=\"watts\",  name=~\".*\"} > 0",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Volts (High)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 7, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(ipmi_sensor_value{host=~\"$hostname\", unit=\"volts\"}[60m]) > 50",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Volts (Low)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 15, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(ipmi_sensor_value{host=~\"$hostname\", unit=\"volts\"}[60m]) < 100",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Fan",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(ipmi_sensor_value{host=~\"$hostname\", unit=\"rpm\"}[30m]) > 0",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ipmi_sensor_value{host=~\"$hostname\", unit=\"degrees_c\"} > 0",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "All values",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(ipmi_sensor_value{host=~\"$hostname\"}) by (unit)",
       "legendFormat": "{{ unit }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Internal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(internal_gather_errors{host=~\"$hostname\"}[10m]) > 0",
       "legendFormat": "{{ input }}"
      }
     ]
    },
    {
     "title": "Gather time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "internal_gather_gather_time_ns{host=~\"$hostname\"}",
       "legendFormat": "{{ input }}"
      }
     ]
    },
    {
     "title": "Metrics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk(5, delta(internal_gather_metrics_gathered{host=~\"$hostname\"}[10m]))",
       "legendFormat": "{{ input }}"
      }
     ]
    },
    {
     "title": "Metrics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk(5, delta(internal_gather_metrics_gathered{host=~\"$hostname\"}[10m]))",
       "legendFormat": "{{ input }}"
      }
     ]
    }
   ]
  },
  {
   "title": "S.M.A.R.T",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "smart_attribute_raw_value{host=~\"$hostname\", name=~\"Temp.*\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Units Write & Read",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 5, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(smart_attribute_raw_value{host=~\"$hostname\", name=~\"Data_Units_Read\"}[10m])",
       "legendFormat": "{{device}}-r"
      },
      {
       "expr": "rate(smart_attribute_raw_value{host=~\"$hostname\", name=~\"Data_Units_Written\"}[10m])",
       "legendFormat": "{{device}}-w"
      }
     ]
    },
    {
     "title": "Power_On_Hours",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 7 },
     "yaxes": [
      { "format": "h" }
     ],
     "targets": [
      {
       "expr": "smart_attribute_raw_value{host=~\"$hostname\", name=~\"Power_On_Hours\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Power_On per seconds",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(smart_attribute_raw_value{host=~\"$hostname\", name=~\"Power_On_Hours\"}[1h])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Exit Status",
     "type": "graph",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "smart_device_exit_status{host=~\"$hostname\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Busy Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(smart_attribute_raw_value{host=~\"$hostname\", name=~\"Controller_Busy_Time\"}[10m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Command Read & Write",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 5, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(smart_attribute_raw_value{host=~\"$hostname\", name=~\"Host_Read_Commands\"}[10m])",
       "legendFormat": "{{device}}-r"
      },
      {
       "expr": "rate(smart_attribute_raw_value{host=~\"$hostname\", name=~\"Host_Write_Commands\"}[10m])",
       "legendFormat": "{{device}}-w"
      }
     ]
    },
    {
     "title": "Percent Used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "smart_attribute_raw_value{host=~\"$hostname\", name=~\"Percentage_Used\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Health OK",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "smart_device_health_ok{host=~\"$hostname\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Available Spare",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "smart_attribute_raw_value{host=~\"$hostname\", name=\"Available_Spare\"}",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Chrony",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stratum",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "chrony_system_time{host=~\"$hostname\"}",
       "legendFormat": "{{stratum}} - {{reference_id}}"
      }
     ]
    },
    {
     "title": "skew",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(chrony_skew{host=~\"$hostname\"}) by (host)",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "frequency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 11, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(chrony_frequency{host=~\"$hostname\"}) by (host)",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "chrony_root_delay",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(chrony_root_delay{host=~\"$hostname\"}) by (host)",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "Last offset",
     "type": "graph",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "chrony_last_offset{host=~\"$hostname\"}",
       "legendFormat": "last offset"
      }
     ]
    },
    {
     "title": "chrony_update_interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 13, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(chrony_update_interval{host=~\"$hostname\"}) by (host)",
       "legendFormat": "{{ host }}"
      }
     ]
    }
   ]
  }
 ]
}